theme: jekyll-theme-cayman
title: LDAPCP
description: Most popular, free and open source claims provider for SharePoint 2013 and 2016
show_downloads: true
repository: Yvand/LDAPCP
timezone: Europe/Paris