theme: jekyll-theme-cayman
title: LDAPCP claims provider for SharePoint
description: This claims provider for SharePoint 2013 and 2016 queries Active Directory and LDAP servers to enhance people picker with a great search experience in federated authentication (typically ADFS).