resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
steps:
- powershell: |
   # Create the local directory if it doesn't exist
   $localPath = "$(System.DefaultWorkingDirectory)\LDAPCP"
   if ((Test-Path -Path $localPath -PathType Container) -eq $false) {
       New-Item -ItemType Directory -Path $localPath
   }
   
   Write-Output ("Copy files from Azure storage account")
   $azureContext = New-AzureStorageContext $(AzureStorageAccountName) $(AzureStorageAccountKey)
   $azureShare = Get-AzureStorageShare $(AzureStorageShareName) –Context $azureContext
   Get-AzureStorageFileContent –Share $azureShare –Path "Resources\LDAPCP.snk" "$localPath\LDAPCP.snk"
   Get-AzureStorageFileContent –Share $azureShare –Path "Resources\SharePoint 2013\Microsoft.SharePoint.dll" "$localPath\Microsoft.SharePoint.dll"
   
   Write-Output ("Add assembly Microsoft.SharePoint.dll to the GAC")
   [System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
   $publish = New-Object System.EnterpriseServices.Internal.Publish
   $publish.GacInstall("$localPath\Microsoft.SharePoint.dll")
  displayName: 'Import resources'
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-Task@1
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: |
     AssemblyInfo.cs
    Title: LDAPCP
    Product: LDAPCP
    Description: 'This claims provider connects SharePoint with Active Directory and LDAP servers to provide a great search experience in the people picker with federated authentication'
    Company: GitHub.com/Yvand
    Copyright: 'Copyright © $(date:yyyy), Yvan Duhamel, All rights reserved'
    Trademark: LDAPCP
    VersionNumber: 1.0.0.0
    FileVersionNumber: '$(MajorMinorVersion).*.*'
    InformationalVersion: 1.0.0.0
- task: VSBuild@1
  displayName: 'Build LDAPCP solution'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:IsPackaging=true'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    downloadType: specific
    downloadPath: '$(Parameters.downloadPath)'
  enabled: false
- task: CopyFiles@2
  displayName: 'Copy artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/$(BuildConfiguration)/**/?(*.wsp|*.dll|*.pdb)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'